# Generated by Django 4.1.3 on 2022-12-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfce', models.CharField(max_length=2)),
                ('ip', models.CharField(max_length=16)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdvs', to='store.store')),
            ],
        ),
    ]
