# Generated by Django 4.1.3 on 2022-12-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_pdv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdv',
            old_name='store_id',
            new_name='store',
        ),
    ]
