# Generated by Django 4.1.3 on 2023-04-22 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maccontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macaddress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 22, 17, 50, 6, 716461, tzinfo=datetime.timezone.utc)),
        ),
    ]
