# Generated by Django 4.1.3 on 2023-04-22 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maccontrol', '0002_macaddress_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macaddress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
