# Generated by Django 4.1.3 on 2023-04-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maccontrol', '0003_alter_macaddress_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='macaddress',
            name='allowed_days',
            field=models.IntegerField(default=0),
        ),
    ]
