# Generated by Django 4.1.3 on 2023-04-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maccontrol', '0004_macaddress_allowed_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macaddress',
            name='allowed_days',
            field=models.DateTimeField(default='2099-01-01 00:00:00'),
        ),
    ]
