# Generated by Django 4.1.3 on 2023-04-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maccontrol', '0005_alter_macaddress_allowed_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macaddress',
            name='allowed_days',
            field=models.DateTimeField(),
        ),
    ]
